export const VAR = 'var'
export const STRING = 'str'
export const NUM = 'num'
export const PUNC = 'punc'
export const BLOCK = 'block'
export const ASSIGN = 'assign'
export const REFERENCE = 'reference'

export const CLASS = 'Class'
export const PROPERTY = 'Property'

export const DESCRIPTION = 'description'
export const SUBCLASSOF = 'subClassOf'
export const PROPERTIES = 'properties'
export const RANGE = 'range'

export const PROPERTY_REQUIRED = 'required'
export const PROPERTY_MIN_ITEMS = 'minItems'
export const PROPERTY_MAX_ITEMS = 'maxItems'
export const PROPERTY_ARRAY = 'array'
export const PROPERTY_INDEX = 'index'

export const RANGE_VALUES = 'values'
export const RANGE_MIN = 'min'
export const RANGE_MAX = 'max'
export const RANGE_REGEX = 'regex'
